<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Action Name' => '',
  'Alias' => '',
  'Ancestor Guid' => '',
  'Begin' => 'Anfang',
  'Cancel' => 'Abbrechen',
  'Check Access Create' => 'Erstellen',
  'Check Access Delete' => 'Löschen',
  'Check Access Read' => 'Lesen',
  'Check Access Update' => 'Aktualisieren',
  'Container' => '',
  'Content' => 'Inhalt',
  'Controller' => '',
  'Create' => 'Erstellen',
  'Created At' => 'Erstellt am',
  'Created By' => 'Erstellt von',
  'Custom Data' => 'Benutzerdefinierte Daten',
  'End' => 'Ende',
  'Fields with' => '',
  'Guid' => '',
  'ID' => '',
  'Id0' => '',
  'Invalid request. Please do not repeat this request again.' => 'Ungültige Anfrage. Bitte wiederholen Sie diese Anfrage nicht.',
  'Keywords' => 'Schlüsselwörter',
  'Label' => 'Bezeichnung',
  'Language' => 'Sprache',
  'Manage' => 'Verwalten',
  'Model' => 'Modell',
  'Modified At' => 'Geändert am',
  'Modified By' => 'Geändert von',
  'Module' => 'Modul',
  'Owner' => 'Eigentümer',
  'P3 Widget' => '',
  'P3 Widget Meta' => '',
  'P3 Widget Metas' => '',
  'P3 Widget Translation' => '',
  'P3 Widget Translations' => '',
  'P3 Widgets' => '',
  'P3Widget' => '',
  'P3WidgetMeta' => '',
  'Properties' => 'Einstellungen',
  'Rank' => 'Rang',
  'Request Param' => '',
  'Save' => 'Speichern',
  'Search' => 'Suchen',
  'Session Param' => '',
  'Status' => '',
  'The requested page does not exist.' => 'Die angeforderte Seite ist nicht vorhanden.',
  'Tree Parent' => '',
  'Tree Position' => '',
  'TreeParent' => '',
  'Type' => 'Typ',
  'Update' => 'Aktualisieren',
  'are required' => '',
  'help.actionName' => '',
  'help.ancestor_guid' => '',
  'help.begin' => '',
  'help.checkAccessCreate' => '',
  'help.checkAccessDelete' => '',
  'help.checkAccessRead' => '',
  'help.checkAccessUpdate' => '',
  'help.containerId' => '',
  'help.controllerId' => '',
  'help.createdAt' => '',
  'help.createdBy' => '',
  'help.customData' => '',
  'help.end' => '',
  'help.guid' => '',
  'help.keywords' => '',
  'help.label' => '',
  'help.language' => '',
  'help.model' => '',
  'help.modifiedAt' => '',
  'help.modifiedBy' => '',
  'help.moduleId' => '',
  'help.owner' => '',
  'help.rank' => '',
  'help.requestParam' => '',
  'help.sessionParam' => '',
  'help.status' => '',
  'help.treePosition' => '',
  'help.type' => '',
);
