<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Action Name' => 'Action',
  'Alias' => 'Klasse/Alias',
  'Container' => '',
  'Content Html' => 'HTML-Inhalt',
  'Controller' => 'Controller',
  'Default Content Html' => 'HTML-Inhalt',
  'Default Properties Json' => 'Eigenschaften',
  'Module' => 'Modul',
  'P3 Widget' => 'Widget',
  'P3 Widget Translation' => 'Widget-Übersetzung',
  'P3 Widget Translations' => 'Widget-Übersetzungen',
  'P3 Widgets' => 'Widgets',
  'Properties Json' => 'Eigenschaften',
  'Rank' => 'Rang',
  'Request Param' => 'Anfrage-Parameter',
  'Session Param' => 'Session-Parameter',
  'help.default_properties_json' => '',
  'relation.P3Widget' => 'Basisdatensatz',
  'relation.P3WidgetTranslations' => 'Übersetzungen',
  'tooltip.action_name' => '',
  'tooltip.alias' => '',
  'tooltip.container_id' => '',
  'tooltip.content_html' => '',
  'tooltip.controller_id' => '',
  'tooltip.created_at' => 'Erstellungsdatum',
  'tooltip.default_content_html' => '',
  'tooltip.default_properties_json' => '',
  'tooltip.id' => '',
  'tooltip.language' => 'Sprache der Übersetzung',
  'tooltip.module_id' => '',
  'tooltip.p3_widget_id' => '',
  'tooltip.properties_json' => '',
  'tooltip.rank' => 'Position innerhalb des Containers',
  'tooltip.request_param' => '$_GET-Parameter, z.B. Seiten-ID',
  'tooltip.session_param' => '',
  'tooltip.status' => '',
  'tooltip.updated_at' => 'Änderungsdatum',
  'Access Delete' => 'Löschen',
  'Access Domain' => 'Domain',
  'Access Owner' => 'Eigentümer',
  'Access Read' => 'Lesen',
  'Access Update' => 'Aktualisieren',
  'Copied From' => 'Kopiert von',
  'Created At' => 'Erstellt am',
  'ID' => 'ID',
  'Language' => 'Sprache',
  'Name' => 'Name (Identifier)',
  'Status' => 'Status',
  'Updated At' => 'Aktualisiert am',
  'tooltip.access_delete' => 'Rolle, welche das Recht besitzt diese Seite zu löschen.',
  'tooltip.access_domain' => 'Zugriffseinschränkung über die Anwendungssprache.',
  'tooltip.access_owner' => 'Besitzer dieses Datensatzes.',
  'tooltip.access_read' => 'Rolle, welche das Recht besitzt diese Seite zu lesen/aufzurufen.',
  'tooltip.access_update' => 'Rolle, welche das Recht besitzt diese Seite zu aktualisieren.',
  'tooltip.copied_from_id' => 'Datensatz-ID von welcher dieser Datensatz kopiert wurde.',
  'tooltip.name_id' => 'Name-ID, z.B. zur Verwendung in der Navigationsauswahl "Navbar".',
);
