<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Advanced Search' => '',
  'Cancel' => '',
  'Clear' => '',
  'Clear Search' => '',
  'Create' => '',
  'Data' => '',
  'Delete' => '',
  'Do not use double quotes (") for keys and/or values!' => '',
  'Do you want to delete this item?' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'Invalid request. Please do not repeat this request again.' => '',
  'Manage' => '',
  'Overview' => '',
  'Playground' => '',
  'Relations' => '',
  'Reset' => '',
  'Reset all Properties?' => '',
  'Save' => '',
  'Search' => '',
  'Switch to view mode to edit related records.' => '',
  'The requested page does not exist.' => '',
  'This module provides a control called P3WidgetManager, along with an administration interface.<br/>
       The P3WidgetManager allows you to dynamically create any type of widget.' => '',
  'This module requires installation.' => '',
  'Translations' => '',
  'Update' => '',
  'View' => '',
  'View Mode' => '',
  'Widget Playground' => '',
  'Widgets' => '',
);
