<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Action Name' => '',
  'Alias' => '',
  'Ancestor Guid' => '',
  'Begin' => '',
  'Cancel' => '',
  'Check Access Create' => '',
  'Check Access Delete' => '',
  'Check Access Read' => '',
  'Check Access Update' => '',
  'Container' => '',
  'Content' => '',
  'Controller' => '',
  'Create' => '',
  'Created At' => '',
  'Created By' => '',
  'Custom Data' => '',
  'End' => '',
  'Fields with' => '',
  'Guid' => '',
  'ID' => '',
  'Id0' => '',
  'Invalid request. Please do not repeat this request again.' => '',
  'Keywords' => '',
  'Label' => '',
  'Language' => '',
  'Manage' => '',
  'Model' => '',
  'Modified At' => '',
  'Modified By' => '',
  'Module' => '',
  'Owner' => '',
  'P3 Widget' => '',
  'P3 Widget Meta' => '',
  'P3 Widget Metas' => '',
  'P3 Widget Translation' => '',
  'P3 Widget Translations' => '',
  'P3 Widgets' => '',
  'P3Widget' => '',
  'P3WidgetMeta' => '',
  'Properties' => '',
  'Rank' => '',
  'Request Param' => '',
  'Save' => '',
  'Search' => '',
  'Session Param' => '',
  'Status' => '',
  'The requested page does not exist.' => '',
  'Tree Parent' => '',
  'Tree Position' => '',
  'TreeParent' => '',
  'Type' => '',
  'Update' => '',
  'are required' => '',
  'help.actionName' => '',
  'help.alias' => 'Widget Type',
  'help.ancestor_guid' => '',
  'help.begin' => '',
  'help.checkAccessCreate' => '',
  'help.checkAccessDelete' => '',
  'help.checkAccessRead' => '',
  'help.checkAccessUpdate' => '',
  'help.containerId' => 'Container of this widget',
  'help.controllerId' => '',
  'help.createdAt' => '',
  'help.createdBy' => '',
  'help.customData' => '',
  'help.end' => '',
  'help.guid' => '',
  'help.keywords' => '',
  'help.label' => '',
  'help.language' => 'Language of the translated properties and content below',
  'help.model' => '',
  'help.modifiedAt' => '',
  'help.modifiedBy' => '',
  'help.moduleId' => '',
  'help.owner' => '',
  'help.rank' => 'Position within the container',
  'help.requestParam' => '',
  'help.sessionParam' => '',
  'help.status' => '',
  'help.treePosition' => '',
  'help.type' => '',
);
