<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Access Delete' => '',
  'Access Domain' => '',
  'Access Owner' => '',
  'Access Read' => '',
  'Access Update' => '',
  'Action Name' => '',
  'Alias' => '',
  'Container' => '',
  'Content Html' => '',
  'Controller' => '',
  'Copied From' => '',
  'Created At' => '',
  'Default Content Html' => '',
  'Default Properties Json' => '',
  'ID' => '',
  'Language' => '',
  'Module' => '',
  'Name' => '',
  'P3 Widget' => '',
  'P3 Widget Translation' => '',
  'P3 Widget Translations' => '',
  'P3 Widgets' => '',
  'Properties Json' => '',
  'Rank' => '',
  'Request Param' => '',
  'Session Param' => '',
  'Status' => '',
  'Updated At' => '',
  'help.default_properties_json' => '',
  'relation.P3Widget' => '',
  'relation.P3WidgetTranslations' => '',
  'tooltip.access_delete' => '',
  'tooltip.access_domain' => '',
  'tooltip.access_owner' => '',
  'tooltip.access_read' => '',
  'tooltip.access_update' => '',
  'tooltip.action_name' => '',
  'tooltip.alias' => '',
  'tooltip.container_id' => '',
  'tooltip.content_html' => '',
  'tooltip.controller_id' => '',
  'tooltip.copied_from_id' => '',
  'tooltip.created_at' => '',
  'tooltip.default_content_html' => '',
  'tooltip.default_properties_json' => '',
  'tooltip.id' => '',
  'tooltip.language' => '',
  'tooltip.module_id' => '',
  'tooltip.name_id' => '',
  'tooltip.p3_widget_id' => '',
  'tooltip.properties_json' => '',
  'tooltip.rank' => '',
  'tooltip.request_param' => '',
  'tooltip.session_param' => '',
  'tooltip.status' => '',
  'tooltip.updated_at' => '',
);
